#!/usr/bin/python3
def raise_exception():
    a = "a"
    b = 1
    c = a + b
    return c
